version: '3.8'

services:
  frps:
    image: ghcr.io/fatedier/frps:v0.61.2
    container_name: frps
    restart: always
    ports:
      - "7001:7000"   # FRP 连接端口
      - "7500:7500"   # Web Dashboard 端口
    volumes:
      - ./frps.toml:/etc/frp/frps.toml
    command: ["-c", "/etc/frp/frps.toml"]
