version: '3.8'

services:
  frps:
    image: ghcr.io/fatedier/frps:v0.53.0
    container_name: frps
    restart: always
    network_mode: host
    ports:
      - "7001:7000"   # FRP 连接端口
      - "7500:7500"   # Web Dashboard 端口
    volumes:
      - ./frps.ini:/etc/frp/frps.ini
    command: ["-c",  "/etc/frp/frps.ini"]